print("---------------------------")

print("try_except")



# try:
#     print("hello")
#     raise NameError("HiThere!!!")
#     print("hello2")