print("---------------------")
print("try_exception")


# try:
#     path =r'ch13\exception\myfile.txt'
#     mode ="w"
#     f = open(path,mode)
#     f.write("hello")
